parameters:
  name: ''
  displayName: ''
  installLlvm: ''
  matrix: {}
  msBuildArgs: ''
  platform: ''
  solution: ''
  vcpkgInstallArgs: ''
  vmImage: ''
jobs:
- job: ${{ parameters.name }}
  displayName: ${{ parameters.displayName }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  variables:
    installLlvm: ${{ parameters.installLlvm }}
    msBuildArgs: ${{ parameters.msBuildArgs }}
    platform: ${{ parameters.platform }}
    solution: ${{ parameters.solution }}
    vcpkgInstallArgs: ${{ parameters.vcpkgInstallArgs }}
  strategy:
    matrix:
      ${{ insert }}: ${{ parameters.matrix }}
  steps:
  - checkout: self
    submodules: recursive
  - powershell: |
      Set-PSDebug -Trace 1
      choco install llvm
      Invoke-WebRequest https://yuo.be/ci/azure-llvm-msbuild-vs2019.zip -OutFile azure-llvm-msbuild-vs2019.zip
      Expand-Archive azure-llvm-msbuild-vs2019.zip azure-llvm-msbuild-vs2019
      cmd /c azure-llvm-msbuild-vs2019\install-enterprise.bat
    condition: variables.installLlvm
    displayName: Install LLVM
  - powershell: |
      Set-PSDebug -Trace 1
      vcpkg version
      vcpkg integrate install
      vcpkg install $(vcpkgInstallArgs)
    condition: variables.vcpkgInstallArgs
    displayName: Install dependencies
  - task: VSBuild@1
    displayName: Build
    inputs:
      solution: $(solution)
      platform: $(platform)
      configuration: $(configuration)
      msbuildArgs: /m $(msBuildArgs)
