parameters:
  name: ''
  displayName: ''
  installLlvm: ''
  matrix: {}
  msBuildArgs: ''
  platform: ''
  solution: ''
  vcpkgPackages: ''
  vmImage: ''
jobs:
- job: ${{ parameters.name }}
  displayName: ${{ parameters.displayName }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  variables:
    installLlvm: ${{ parameters.installLlvm }}
    msBuildArgs: ${{ parameters.msBuildArgs }}
    platform: ${{ parameters.platform }}
    solution: ${{ parameters.solution }}
    vcpkgPackages: ${{ parameters.vcpkgPackages }}
  strategy:
    matrix:
      ${{ insert }}: ${{ parameters.matrix }}
  steps:
  - checkout: self
    submodules: recursive
  - powershell: |
      choco install llvm
      svn checkout -r322941 https://github.com/llvm/llvm-project/trunk/llvm/tools/msbuild
      ((Get-Content -path msbuild\install.bat -Raw) -replace '2017\\Professional\\Common7\\IDE\\VC\\VCTargets','2019\Enterprise\MSBuild\Microsoft\VC\v160') | Set-Content -Path msbuild\install-enterprise.bat
      cmd /c msbuild\install-enterprise.bat
    condition: variables.installLlvm
    displayName: Install LLVM
  - powershell: |
      vcpkg integrate install
      vcpkg install $(vcpkgPackages)
    condition: variables.vcpkgPackages
    displayName: Install dependencies
  - task: VSBuild@1
    displayName: Build
    inputs:
      solution: $(solution)
      platform: $(platform)
      configuration: $(configuration)
      msbuildArgs: /m $(msBuildArgs)
