parameters:
  name: ''
  displayName: ''
  installLlvm: ''
  installVcpkg: ''
  matrix: {}
  msBuildArgs: ''
  platform: ''
  solution: ''
  vcpkgPackages: ''
  vmImage: ''
jobs:
- job: ${{ parameters.name }}
  displayName: ${{ parameters.displayName }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  variables:
    installLlvm: ${{ parameters.installLlvm }}
    installVcpkg: ${{ parameters.installVcpkg }}
    msBuildArgs: ${{ parameters.msBuildArgs }}
    platform: ${{ parameters.platform }}
    solution: ${{ parameters.solution }}
    vcpkgPackages: ${{ parameters.vcpkgPackages }}
  strategy:
    matrix:
      ${{ insert }}: ${{ parameters.matrix }}
  steps:
  - checkout: self
    submodules: recursive
  - powershell: |
      Invoke-WebRequest -Uri "https://github.com/Microsoft/vsixbootstrapper/releases/download/1.0.37/VSIXBootstrapper.exe" -Out "VSIXBootstrapper.exe"
      Invoke-WebRequest -Uri "https://llvmextensions.gallerycdn.vsassets.io/extensions/llvmextensions/llvm-toolchain/1.0.340780/1535663999089/llvm.vsix" -Out "llvm.vsix"
      .\VSIXBootstrapper.exe /quiet llvm.vsix
      choco install llvm
    condition: variables.installLlvm
    displayName: Install LLVM
  - script: |
      git clone https://github.com/Microsoft/vcpkg.git
      vcpkg\bootstrap-vcpkg.bat
    condition: variables.installVcpkg
    displayName: Install Vcpkg
  - powershell: |
      $vcpkgPath = If ('$(installVcpkg)') { '.\vcpkg\vcpkg' } Else { 'vcpkg' }
      & $vcpkgPath integrate install
      & $vcpkgPath install $(vcpkgPackages)
    condition: variables.vcpkgPackages
    displayName: Install dependencies
  - task: VSBuild@1
    displayName: Build
    inputs:
      solution: $(solution)
      platform: $(platform)
      configuration: $(configuration)
      msbuildArgs: /m $(msBuildArgs)
