variables:
  solution: vc16/columns_ui-public.sln
  llvmMsBuildArgs: /p:PlatformToolset=ClangCL;UseLldLink=True;VcpkgAutoLink=False;WholeProgramOptimization=False;SpectreMitigation=
  vcpkgInstallArgs: 'ms-gsl range-v3 wil --overlay-ports=$(System.DefaultWorkingDirectory)\ports'
jobs:
- template: job-build.yml
  parameters:
    displayName: VS 2019 LLVM
    matrix:
      Debug:
        configuration: Debug
      Release:
        configuration: Release
    msBuildArgs: ${{ variables.llvmMsBuildArgs }}
    name: vs2019_llvm
    platform: Win32
    solution: ${{ variables.solution }}
    vcpkgInstallArgs: ${{ variables.vcpkgInstallArgs }}
    vmImage: windows-2019
- template: job-build.yml
  parameters:
    displayName: VS 2019 v142
    matrix:
      Debug:
        configuration: Debug
      Release:
        configuration: Release
    name: vs2019_v142
    platform: Win32
    solution: ${{ variables.solution }}
    vcpkgInstallArgs: ${{ variables.vcpkgInstallArgs }}
    vmImage: windows-2019
