variables:
  solution: vc16/columns_ui-public.sln
  llvmMsBuildArgs: /p:PlatformToolset=llvm;UseLldLink=False;SpectreMitigation=
  vcpkgPackages: 'ms-gsl range-v3'
jobs:
- template: job-build.yml
  parameters:
    displayName: VS 2019
    installVcpkg: 'true'
    matrix:
      LLVM Debug:
        configuration: Debug
        installLlvm: 'true'
        msBuildArgs: ${{ variables.llvmMsBuildArgs }}
      LLVM Release:
        configuration: Release
        installLlvm: 'true'
        msBuildArgs: ${{ variables.llvmMsBuildArgs }}
      v142 Debug:
        configuration: Debug
      v142 Release:
        configuration: Release
    name: vs2019
    platform: Win32
    solution: ${{ variables.solution }}
    vcpkgPackages: ${{ variables.vcpkgPackages }}
    vmImage: windows-2019
