variables:
  solution: vc15/columns_ui-public.sln
  installVcpkg: ''
  installLlvm: ''
  msBuildArgs: ''
  platform: Win32
  vcpkgPackages: 'ms-gsl range-v3'
  LlvmMsBuildArgs: /p:PlatformToolset=llvm;UseLldLink=False;SpectreMitigation=
  vs2019MsBuildArgs: /p:PlatformToolset=v142
jobs:
- job: build
  displayName: Build
  strategy:
    matrix:
      VS 2017 v141 Release:
        configuration: Release
        vmImage: vs2017-win2016
      VS 2017 v141 Debug:
        configuration: Debug
        vmImage: vs2017-win2016
      VS 2019 v142 Release:
        configuration: Release
        installVcpkg: 'true'
        msBuildArgs: $(vs2019MsBuildArgs)
        vmImage: windows-2019
      VS 2019 v142 Debug:
        configuration: Debug
        installVcpkg: 'true'
        msBuildArgs: $(vs2019MsBuildArgs)
        vmImage: windows-2019
      VS 2017 LLVM Release:
        configuration: Release
        installLlvm: 'true'
        msBuildArgs: $(LlvmMsBuildArgs)
        vmImage: vs2017-win2016
      VS 2017 LLVM Debug:
        configuration: Debug
        installLlvm: 'true'
        msBuildArgs: $(LlvmMsBuildArgs)
        vmImage: vs2017-win2016
  pool:
    vmImage: $(vmImage)
  steps:
  - template: step-build.yml
