variables:
  solution: vc16/columns_ui-public.sln
  llvmMsBuildArgs: /p:PlatformToolset=llvm;UseLldLink=False;SpectreMitigation=
  vcpkgPackages: 'ms-gsl range-v3'
jobs:
- template: job-build.yml
  parameters:
    displayName: VS 2019 LLVM
    installLlvm: 'true'
    matrix:
      Debug:
        configuration: Debug
      Release:
        configuration: Release
    msBuildArgs: ${{ variables.llvmMsBuildArgs }}
    name: vs2019_llvm
    platform: Win32
    solution: ${{ variables.solution }}
    vcpkgPackages: ${{ variables.vcpkgPackages }}
    vmImage: windows-2019
- template: job-build.yml
  parameters:
    displayName: VS 2019 v142
    matrix:
      Debug:
        configuration: Debug
      Release:
        configuration: Release
    name: vs2019_v142
    platform: Win32
    solution: ${{ variables.solution }}
    vcpkgPackages: ${{ variables.vcpkgPackages }}
    vmImage: windows-2019
